<a href="https://colab.research.google.com/github/SergeyMalyshevsky/Samsung-Neural-Network-Course/blob/master/Samsung_1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

In [0]:
import torch

**Создание тензоров**

In [4]:
# создать матрицу 3х4 и заполнить нулями
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# создать тензор 3х4х3 и заполнить единицами
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
# создать тензор на основе списков
torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [0]:
# положить объект в переменную x
x = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

**Вывод размера тензора**

In [10]:
# узнать размер тензора x. Способ 1
x.size()

torch.Size([3, 4])

In [12]:
# узнать размер тензора x. Способ 2
x.shape

torch.Size([3, 4])

**Получение строк, столбцов и элементов тензора**

In [13]:
# получить первую строчку
x[0]

tensor([1., 2., 3., 4.])

In [14]:
# получить вторую строчку
x[1]

tensor([5., 6., 7., 8.])

In [16]:
# получить первый столбец
x[:, 0]

tensor([1., 5., 9.])

In [15]:
# получить элемент по индексу
x[0, 0]

tensor(1.)

**Операции с тензором**

In [17]:
# прибавить к тензору число
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [18]:
# возвести тензор в квадрат
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

**Операции с тензорами**