<a href="https://colab.research.google.com/github/SergeyMalyshevsky/Samsung-Neural-Network-Course/blob/master/Samsung_2_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

# создаем тензор
# атрибут requeres_grad=True превращает тензор-константу в тензор переменную
# и сообщает, что данный тензор является переменной, 
# по которой нужно будет считать градиенты
x = torch.tensor([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.],
    [9., 10., 11., 12.]
], requires_grad=True)

# переносим вычисления на GPU если он есть
device = torch.device('cuda:0' if torch.cuda.is_available() 
                      else 'cpu')
x = x.to(device)

# определяем функцию
function = 10 * (x ** 2).sum()

# вызываем backward, результат записывается в свойство x.grad
function.backward()

print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


In [4]:
# показать последнюю функцию
print(function.grad_fn)
# показать предпоследнюю функцию
print(function.grad_fn.next_functions[0][0])
# показать предпредпоследнюю функцию
print(function.grad_fn.next_functions[0][0].next_functions[0][0])
# показать предпредпредпоследнюю функцию
print(function.grad_fn.next_functions[0][0].next_functions[0][0]
      .next_functions[0][0])

Задание

In [10]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)

# определяем функцию
function = torch.log(torch.log((w + 7))).prod()

# вызываем backward, результат записывается в свойство x.grad
function.backward()

print(w.grad, '<- gradient')

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]]) <- gradient


In [0]:
x.data -= 0.001 * x.grad

In [13]:
# нижнее подчеркивание на конце метода означает, что он будет применен к тому 
# объекту над которым выполняется(inplace операции)

# метод zero_() обнуляет градиенты
x.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Создание функций для градиентного спуска**

In [0]:
import torch

x = torch.tensor([8., 8.], requires_grad=True)

optimizer = torch.optim.SGD([x], lr=0.001)

def function_parabola(variable):
  return 10 * (variable ** 2).sum()

def make_gradient_step(loss_function, variable):
  loss_function_result = loss_function(variable)
  loss_function_result.backward()
  #variable.data -= 0.001 * variable.grad
  optimizer.step()
  #variable.grad.zero_()
  optimizer.zero_grad()
  
for i in range(500):
  make_gradient_step(function_parabola, x)

In [21]:
%matplotlib inline

show_contours(function_parabola)
plt.scatter(np.array(var_history)[:,0], np.array(var_history)[:, 1], s=10,
           c='r')

NameError: ignored