<a href="https://colab.research.google.com/github/SergeyMalyshevsky/Samsung-Neural-Network-Course/blob/master/Samsung_1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

In [0]:
import torch

**Создание тензоров**

In [4]:
# создать матрицу 3х4 и заполнить нулями
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# создать тензор 3х4х3 и заполнить единицами
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
# создать тензор на основе списков
torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [0]:
# положить объект в переменную x
x = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

**Вывод размера тензора**

In [10]:
# узнать размер тензора x. Способ 1
x.size()

torch.Size([3, 4])

In [12]:
# узнать размер тензора x. Способ 2
x.shape

torch.Size([3, 4])

**Получение строк, столбцов и элементов тензора**

In [13]:
# получить первую строчку
x[0]

tensor([1., 2., 3., 4.])

In [14]:
# получить вторую строчку
x[1]

tensor([5., 6., 7., 8.])

In [16]:
# получить первый столбец
x[:, 0]

tensor([1., 5., 9.])

In [15]:
# получить элемент по индексу
x[0, 0]

tensor(1.)

**Операции с тензором**

In [17]:
# прибавить к тензору число
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [18]:
# возвести тензор в квадрат
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

**Операции с тензорами**

In [0]:
# создаем новый тензор
y = torch.Tensor([
    [12, 11, 10, 9],
    [8, 7, 6, 5],
    [4, 3, 2, 1]
])

In [20]:
# складываем два тензора
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [22]:
# умножаем тензоры
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [21]:
# делим тензор х на тензор y
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [23]:
# получаем остаток от деления тензора x на тензор y
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

Примеры

In [0]:
a = torch.ones([5, 4])
b = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20]
])

In [25]:
a % b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4], 
                  [5,6,7,8], 
                  [9,10,11,12], 
                  [13,14,15,16], 
                  [17,18,19,20]
                 ])

In [27]:
a[4] + b[0]

tensor([2., 3., 4., 5.])

**Выполнение математических функций над тензорами**

In [28]:
# экспонента
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [29]:
# натуральный логарифм
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [30]:
# синус
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

**Логические операции с тензорами**

In [32]:
# поэлементное сравнение, в результате получается 0(ложь) или 1(истина)
x > 3

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [33]:
# наложение маски на тензор. Способ 1
mask = x > 3
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [34]:
# наложение маски на тензор. Способ 2
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

**Сумма всех элементов тензора**

In [35]:
x.sum()

tensor(78.)

**Клонирование тензора**

In [37]:
y = x.clone()
y[0, 0] = 999
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [38]:
y

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

**Типы данных тензора**

In [41]:
# узнать тип элементов в тензоре
x.dtype

torch.float32

In [42]:
# изменить тип элементов в тензоре
x = x.double()
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)

In [43]:
x = x.int()
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)

In [44]:
x = x.float()
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

**Взаимодействие с NumPy**

In [0]:
import numpy as np

In [49]:
# создать массив numpy
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# преобразовать массив numpy в тензор pytorch
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [52]:
# преобразовать тензор pytorch в массив numpy
x = x.numpy()
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])